import { INestApplication, ValidationPipe, VersioningType } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import helmet from 'helmet';
import { AppModule } from './app.module';

function setupVersioning(app: INestApplication) {
  app.enableVersioning({
    type: VersioningType.URI,
  })
}

function setupValidation(app: INestApplication) {
  app.useGlobalPipes(new ValidationPipe({
    whitelist: true,
    transformOptions: { enableImplicitConversion: true },
  }));
}

function setupSwagger(app: INestApplication) {
  // https://docs.nestjs.com/openapi/introduction
  const docs = new DocumentBuilder()
    .setTitle('Demo API Documentation')
    .setDescription('This documentation is generated by <a href="https://docs.nestjs.com/openapi/introduction" target="_blank">@nestjs/swagger</a> and <a href="https://docs.nestjs.com/openapi/cli-plugin" target="_blank">cli-plugin</a>.')
    .addServer(process.env.STAGE_PATH_PREFIX || '')
    .addBearerAuth({ // https://docs.nestjs.com/openapi/security#bearer-authentication
      type: 'http',
      description: `Please enter your accessToken`,
    })
    .setVersion('0.0.0')
    .build();
  const document = SwaggerModule.createDocument(app, docs);
  SwaggerModule.setup('/docs', app, document);
}

export async function createApp() {
  const app = await NestFactory.create(AppModule);
  setupVersioning(app)
  setupValidation(app)
  setupSwagger(app);
  app.use(helmet());
  app.enableCors();
  app.useLogger(['log']) // error < warn < log < debug < verbose
  return app;
}